components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
        email: 
          type: string
        password:
          type: string
    GetUser:
      type: object
      properties:
        email:
         type: string
            